apiVersion: v1
kind: Pod
metadata:
  name: pod-with-resources
  labels:
    component: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

