apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-pod
  labels:
    component: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: nginx-log
      mountPath: /var/log/nginx

  - name: fluentd
    image: my-fluentd:1.6.0.1
    volumeMounts:
    - name: nginx-log
      mountPath: /var/log/nginx
      readOnly: true

  volumes:
  - name: nginx-log
    emptyDir: {}

